GLOBAL.STATES = {
	INIT: -1,
	LOBBY: 0,
	PLAYING: 1,
	JUDGING: 2,
	INTERMISSION: 3
}

GLOBAL.E_JOIN = 0;
GLOBAL.E_QUIT = 1;
GLOBAL.E_DRAW_CARD = 2;
GLOBAL.E_PLAY_CARDS = 3;
GLOBAL.E_SHOW_CARDS = 4;
GLOBAL.E_PICK_WINNER = 5;
GLOBAL.E_DETERMINE_JUDGE = 6;